
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author salacomputocentro.ba
 */
public class conversion extends javax.swing.JFrame {

    /**
     * Creates new form conversion
     */
    public conversion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lista1 = new javax.swing.JComboBox();
        lista2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        contenedor1 = new javax.swing.JTextField();
        contenedor2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        convertir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lista1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "metros", "centimetos ", "milimetros" }));

        lista2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "metros", "centimetros", "milimetros" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DE:");

        contenedor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenedor1ActionPerformed(evt);
            }
        });

        contenedor2.setEditable(false);
        contenedor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenedor2ActionPerformed(evt);
            }
        });

        jLabel2.setText("cantidad");

        convertir.setText("convertir");
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(contenedor2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(contenedor1))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(convertir)
                        .addGap(221, 221, 221))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contenedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(79, 79, 79)
                .addComponent(convertir)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contenedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenedor1ActionPerformed
       
    }//GEN-LAST:event_contenedor1ActionPerformed

    private void contenedor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenedor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contenedor2ActionPerformed

    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
       
        if(lista1.getSelectedIndex()==0 && lista2.getSelectedIndex()==0){
        JOptionPane.showMessageDialog(null,"error");
        
        }else if(lista1.getSelectedIndex()==0 && lista2.getSelectedIndex()==1){
        double cen = Double.parseDouble(contenedor1.getText());
        double can = cen*100;
        String resul = String.valueOf(can);
        contenedor2.setText(resul+"cm");
        
        }else if(lista1.getSelectedIndex()==0 && lista2.getSelectedIndex()==2){
        double cen = Double.parseDouble(contenedor1.getText());
        double can = cen*1000;
        String resul = String.valueOf(can);
        contenedor2.setText(resul+"mm");
        
        
        }else if(lista1.getSelectedIndex()==1 && lista2.getSelectedIndex()==1){
        JOptionPane.showMessageDialog(null,"error");
        
        
        }else if(lista1.getSelectedIndex()==1 && lista2.getSelectedIndex()==0){
        double cen = Double.parseDouble(contenedor1.getText());
        double can = cen/100;
        String resul = String.valueOf(can);
        contenedor2.setText(resul+"m");
        
        
        }else if(lista1.getSelectedIndex()==1 && lista2.getSelectedIndex()==2){
        double cen = Double.parseDouble(contenedor1.getText());
        double can = cen*10;   
         String resul = String.valueOf(can);
        contenedor2.setText(resul+"mm");
        
        
        
        }
        else if(lista1.getSelectedIndex()==2 && lista2.getSelectedIndex()==2){
        JOptionPane.showMessageDialog(null,"error");
        
        
        }else if(lista1.getSelectedIndex()==2 && lista2.getSelectedIndex()==0){
        double cen = Double.parseDouble(contenedor1.getText());
        double can = cen*0.01;
        String resul = String.valueOf(can);
        contenedor2.setText(resul+"m");
        
        
        }else if(lista1.getSelectedIndex()==2 && lista2.getSelectedIndex()==1){
        double cen = Double.parseDouble(contenedor1.getText());
        double can = cen*0.1;   
         String resul = String.valueOf(can);
        contenedor2.setText(resul+"cm");
        
        
        
        }
        
    }//GEN-LAST:event_convertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contenedor1;
    private javax.swing.JTextField contenedor2;
    private javax.swing.JButton convertir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox lista1;
    private javax.swing.JComboBox lista2;
    // End of variables declaration//GEN-END:variables
}
